import assert from 'node:assert/strict';
import {simulate,rawIndicators,mergeFavorites,summarize} from '../assets/engine.mjs';
const p={date:'2026-01-01',capital:100000,days:3,stop:.05,take:.1,fee:0,tax:0,slippage:0,min_fee:0};
const bar=(date,open,high,low,close,other={})=>({date,open,high,low,close,volume:1000,...other});
let checks=0;const test=(name,fn)=>{fn();checks++;console.log('PASS',name)};
test('locked never touches future data',()=>{assert.equal(simulate(null,p).status,'locked')});
test('T+1 valid open',()=>{const r=simulate([bar('2026-01-02',100,104,99,103)],p,{reveal:true});assert.equal(r.entry,100);assert.equal(r.status,'open')});
test('missing open is not replaced with close',()=>{assert.equal(simulate([bar('2026-01-02',null,104,99,103)],p,{reveal:true}).status,'pending')});
test('gap stop uses opening price',()=>{const r=simulate([bar('2026-01-02',100,104,99,103),bar('2026-01-05',80,82,78,80)],p,{reveal:true});assert.equal(r.exit,80);assert.match(r.reason,/跳空/) });
test('same day ambiguity uses stop first',()=>{const r=simulate([bar('2026-01-02',100,120,90,115)],p,{reveal:true});assert.equal(r.exit,95);assert.match(r.reason,/雙觸及/) });
test('corporate action stops simplified model',()=>{const r=simulate([bar('2026-01-02',100,104,99,103,{corporate_action:true})],p,{reveal:true});assert.equal(r.status,'unsupported')});
test('not enough future sessions stays open',()=>{const r=simulate([bar('2026-01-02',100,104,99,103)],p,{reveal:true});assert.equal(r.status,'open');assert.equal(r.return_pct,undefined)});
test('costs decrease return',()=>{const rows=[bar('2026-01-02',100,120,99,115)];const a=simulate(rows,p,{reveal:true});const b=simulate(rows,{...p,fee:.001,tax:.003,slippage:.001,min_fee:20},{reveal:true});assert.ok(b.return_pct<a.return_pct)});
test('invalid capital rejected',()=>assert.throws(()=>simulate([],{...p,capital:-1},{reveal:true})));
test('fractional holding period rejected',()=>assert.throws(()=>simulate([],{...p,days:1.5},{reveal:true})));
test('no compounding overlapping trades',()=>{const s=summarize([{status:'closed',pnl:100,return_pct:10},{status:'open'}]);assert.equal(s.count,1);assert.equal(s.open,1);assert.equal(s.compounded_return,undefined)});
test('delete tombstone is returned',()=>{const r=mergeFavorites({'2330.TW':{active:true}},[{symbol:'2330.TW',active:false}]);assert.equal(r['2330.TW'].active,false)});
test('pending local edits are retained',()=>{const r=mergeFavorites({'2330.TW':{pending:true,note:'keep'}},[{symbol:'2330.TW',note:'remote'}]);assert.equal(r['2330.TW'].note,'keep')});
test('flat Wilder RSI 50',()=>{const rows=Array.from({length:70},(_,i)=>bar(String(i),100,101,99,100));const a=rawIndicators(rows);assert.equal(a.at(-1).rsi,50)});
console.log(JSON.stringify({node_tests:checks,ok:true}));
